# Copyright 2020 The GCR Cleaner Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- id: 'build-cli'
  name: 'docker:20'
  args: [
    'build',
    '--build-arg', 'SERVICE=gcr-cleaner-cli',
    '--tag', 'gcr.io/${PROJECT_ID}/gcr-cleaner-cli',
    '--tag', 'asia-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner-cli',
    '--tag', 'europe-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner-cli',
    '--tag', 'us-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner-cli',
    '.'
  ]
  waitFor: ['-']

- id: 'build-server'
  name: 'docker:20'
  args: [
    'build',
    '--build-arg', 'SERVICE=gcr-cleaner-server',
    '--tag', 'gcr.io/${PROJECT_ID}/gcr-cleaner',
    '--tag', 'asia-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner',
    '--tag', 'europe-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner',
    '--tag', 'us-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner',
    '.'
  ]
  waitFor: ['-']

- id: 'push-cli'
  name: 'docker:20'
  entrypoint: '/bin/sh'
  args:
  - '-euo'
  - 'pipefail'
  - '-c'
  - |-
    docker push gcr.io/${PROJECT_ID}/gcr-cleaner-cli
    docker push asia-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner-cli
    docker push europe-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner-cli
    docker push us-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner-cli
  waitFor: ['build-cli']

- id: 'push-server'
  name: 'docker:20'
  entrypoint: '/bin/sh'
  args:
  - '-euo'
  - 'pipefail'
  - '-c'
  - |-
    docker push gcr.io/${PROJECT_ID}/gcr-cleaner
    docker push asia-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner
    docker push europe-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner
    docker push us-docker.pkg.dev/${PROJECT_ID}/gcr-cleaner/gcr-cleaner
  waitFor: ['build-server']
