before:
  hooks:
    - 'go mod tidy'

builds:
  # cli
  -
    id: 'cli'
    env:
      - 'CGO_ENABLED=0'
      - 'GO111MODULE=on'
      - 'GOPROXY=https://proxy.golang.org,direct'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X={{ .ModulePath }}/internal/version.Name=gcr-cleaner-cli'
      - '-X={{ .ModulePath }}/internal/version.Version={{ .Version }}'
      - '-X={{ .ModulePath }}/internal/version.Commit={{ .FullCommit }}'
      - '-extldflags=-static'
    main: './cmd/gcr-cleaner-cli/main.go'
    binary: 'gcr-cleaner-cli'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    goarch:
      - 'amd64'
      - 'arm64'

  # server
  -
    id: 'server'
    env:
      - 'CGO_ENABLED=0'
      - 'GO111MODULE=on'
      - 'GOPROXY=https://proxy.golang.org,direct'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X={{ .ModulePath }}/internal/version.Name=gcr-cleaner'
      - '-X={{ .ModulePath }}/internal/version.Version={{ .Version }}'
      - '-X={{ .ModulePath }}/internal/version.Commit={{ .FullCommit }}'
      - '-extldflags=-static'
    main: './cmd/gcr-cleaner-server/main.go'
    binary: 'gcr-cleaner'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    goarch:
      - 'amd64'
      - 'arm64'

dockers:
  # cli
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    dockerfile: 'docker/cli.dockerfile'
    ids:
      - 'cli'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-amd64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=gcr-cleaner deletes untagged images in Docker container registries.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=gcr-cleaner'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=gcr-cleaner'
      - '--label=org.opencontainers.image.version={{ .Version }}'
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'arm64'
    dockerfile: 'docker/cli.dockerfile'
    ids:
      - 'cli'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-arm64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-arm64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-arm64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-arm64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-arm64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-arm64'
    build_flag_templates:
      - '--platform=linux/arm64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=gcr-cleaner deletes untagged images in Docker container registries.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=gcr-cleaner'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=gcr-cleaner'
      - '--label=org.opencontainers.image.version={{ .Version }}'

  # server
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    dockerfile: 'docker/server.dockerfile'
    ids:
      - 'server'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-amd64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=gcr-cleaner deletes untagged images in Docker container registries.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=gcr-cleaner'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=gcr-cleaner'
      - '--label=org.opencontainers.image.version={{ .Version }}'
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'arm64'
    dockerfile: 'docker/server.dockerfile'
    ids:
      - 'server'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-arm64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-arm64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-arm64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-arm64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-arm64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-arm64'
    build_flag_templates:
      - '--platform=linux/arm64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=gcr-cleaner deletes untagged images in Docker container registries.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=gcr-cleaner'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=gcr-cleaner'
      - '--label=org.opencontainers.image.version={{ .Version }}'

docker_manifests:
  # cli
  -
    name_template: 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-amd64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-arm64'
  -
    name_template: 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-amd64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-arm64'
  -
    name_template: 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}'
    image_templates:
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-arm64'
  -
    name_template: 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest'
    image_templates:
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-arm64'
  -
    name_template: 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}'
    image_templates:
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:{{ .Version }}-arm64'
  -
    name_template: 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest'
    image_templates:
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest-arm64'

  # server
  -
    name_template: 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-amd64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-arm64'
  -
    name_template: 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest'
    image_templates:
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-amd64'
      - 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-arm64'
  -
    name_template: 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}'
    image_templates:
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-arm64'
  -
    name_template: 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest'
    image_templates:
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-amd64'
      - 'europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-arm64'
  -
    name_template: 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}'
    image_templates:
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:{{ .Version }}-arm64'
  -
    name_template: 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest'
    image_templates:
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-amd64'
      - 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner:latest-arm64'

archives:
  # cli
  -
    id: 'cli'
    format: 'tar.gz'
    builds:
      - 'cli'
    name_template: 'gcr-cleaner-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'

  # server
  -
    id: 'server'
    format: 'tar.gz'
    builds:
      - 'server'
    name_template: 'gcr-cleaner_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'

checksum:
  name_template: 'gcr-cleaner_{{ .Version }}_SHA512SUMS'
  algorithm: 'sha512'

changelog:
  use: 'github'

release:
  draft: false
  mode: 'replace'
