name: 'release'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: 'write'
  packages: 'write'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3' # ratchet:docker/setup-qemu-action@v3

      - uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491' # ratchet:actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: 'docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d' # ratchet:docker/login-action@v3
        with:
          registry: 'asia-docker.pkg.dev'
          username: '_json_key'
          password: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - uses: 'docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d' # ratchet:docker/login-action@v3
        with:
          registry: 'europe-docker.pkg.dev'
          username: '_json_key'
          password: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - uses: 'docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d' # ratchet:docker/login-action@v3
        with:
          registry: 'us-docker.pkg.dev'
          username: '_json_key'
          password: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'import_gpg'
        uses: 'crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4' # ratchet:crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          passphrase: '${{ secrets.GPG_PASSPHRASE }}'

      - uses: 'goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8' # ratchet:goreleaser/goreleaser-action@v5
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GPG_FINGERPRINT: '${{ steps.import_gpg.outputs.fingerprint }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
